github:
  is_project_page: false
encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
future: true
jailed: false
theme: jekyll-theme-slate
title: Results - 3D Human Pose Estimation
description: Real-time 3D Human Pose Estimation with a single RGB-camera for Screen-based Augmented-Reality
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://github.com/tobiascz/Results3DHumanPoseEstimation/tree/master" # the base hostname & protocol for your site, e.g. http://example.com

